

-- local dap = require("dap")
-- local dapui = require("dapui")
-- -- local dap_view = require("dap-view")
--
-- vim.fn.sign_define('DapBreakpoint', {text='🛑', texthl='', linehl='', numhl=''})
--
-- dap.adapters.gdb = {
--     type = "executable",
--     command = "gdb",
--     args = { "--interpreter=dap", "--eval-command", "set print pretty on" }
-- }
--
-- dap.configurations.cpp = {
--     {
--         type = "gdb",
--         request = "launch",
--         name = "Launch a file",
--         program = "${command:pickFile}",
--         console = "integratedTerminal",
--     }
-- }
--
-- -- dap_view.setup({
-- --     auto_toggle = true
-- -- })
--
-- dapui.setup({})
--
--
-- dap.listeners.before.attach.dapui_config = function()
--   dapui.open()
-- end
-- dap.listeners.before.launch.dapui_config = function()
--   dapui.open()
-- end
-- dap.listeners.before.event_terminated.dapui_config = function()
--   dapui.close()
-- end
-- dap.listeners.before.event_exited.dapui_config = function()
--   dapui.close()
-- end
