require("pkg-configs.nvim-treesitter")
require("pkg-configs.mini")
require("pkg-configs.indent-blankline")
require("pkg-configs.which-key")
require("pkg-configs.oil")
require("pkg-configs.mason")
require("pkg-configs.mason-lspconfig")
require("pkg-configs.blink")
require("pkg-configs.terminal")
require("pkg-configs.deadcolumn")
require("pkg-configs.lazydev")
require("pkg-configs.fidget")
require("pkg-configs.hex")
require("pkg-configs.typst-preview")
require("pkg-configs.eyeliner")
-- require("pkg-configs.smear_cursor")
