source = ~/.config/hypr/theme.conf

$fontSize = 16
$fontFamily = JetBrainsMono Nerd Font

$boxHeight = 450
$boxHeightSingle = {{ $boxHeight / 2 }}
$boxBottom = {{ $boxHeightSingle * -1 }}
$borderSize = 2
$borderColor = $sapphire
$imageSize = 100
$userNameOffset = {{ $imageSize * 0.8 }}
$userNameY = {{ $boxHeightSingle - $userNameOffset }}
$clockY = {{ $userNameY - 100 }}
$dateY = {{ $clockY - 70 }}
$inputY = {{ $boxBottom + 80 }}

background {
    color = $mantle
    path = ~/config/wallpapers/earth-behind-moon.jpg
}

shape {
    monitor =
    size = 500, $boxHeight
    position = 0, 0
    halign = center
    valign = center
    rounding = 30
    color = rgba($baseAlphaDD)
    border_size = $borderSize
    border_color = $borderColor
}

image {
    monitor =
    path = ~/.face

    size = $imageSize
    position = 0, $boxHeightSingle
    halign = center
    valign = center
    border_size = $borderSize
    border_color = $borderColor
}

label {
    monitor =
    text = $DESC
    font_size = $fontSize
    font_family = $fontFamily

    position = 0, $userNameY
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = {{ $fontSize * 2.5 }}
    font_family = $fontFamily Bold

    position = 0, $clockY
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] bash -c 'date "+%A, %B %d"'
    font_size = {{ $fontSize * 1.15 }}
    font_family = $fontFamily

    position = 0, $dateY
    halign = center
    valign = center
}

input-field {
    monitor =
    placeholder_text =   Enter Password
    hide_input = false
    font_family = $fontFamily

    size = $boxHeightSingle, {{ $fontSize * 3 }}
    position = 0, $inputY
    halign = center
    valign = center

    outline_thickness = $borderSize
    fade_on_empty = false
    inner_color = $surface0
    outer_color = $borderColor
    font_color = $text
    check_color = $yellow
    fail_color = $red
    capslock_color = $rosewater
}
